name: CI Testing
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - fix/*
    - feature/*

jobs:
  test:
    # Job name is Test
    name: Test
    # This job runs on macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=latest,name=iPhone 11']
        xcode: ['/Applications/Xcode_11.4.app/Contents/Developer']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create Failure Directory
        run: mkdir TestResults
      - name: Install XCTestHTMLReport
        run: bash <(curl -s https://raw.githubusercontent.com/TitouanVanBelle/XCTestHTMLReport/master/install.sh) '2.0.0'
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.4.app
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Run Pod Install
        run: pod install
      - name: List Directory
        run: ls -la
      - name: Build and Test
        run: xcodebuild clean test -workspace ownCloud.xcworkspace -scheme ownCloud -configuration Debug -destination "${destination}" -resultBundlePath TestResults/XCTestResults
        env:
          destination: ${{ matrix.destination }}
      - name: Create XCTestHTMLReport
<<<<<<< HEAD
        if: failure()
          run: xchtmlreport -r TestResults/XCTestResults
      - name: Upload XCTestHTMLReport Artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: XCTestHTMLReport
          path: TestResults/index.html
=======
        if: always()
        run: xchtmlreport -r TestResults/XCTestResults
>>>>>>> 89c3722489263ab043caecf83a39bb1f88793ae9
      - name: Archive Tests Artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: CI-Artifacts
          path: TestResults
