name: CI
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - fix/*
    - feature/*

jobs:
  test:
    # Job name is Test
    name: Test
    # This job runs on macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=latest,name=iPhone 11']
        xcode: ['/Applications/Xcode_11.4.app/Contents/Developer']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.4.app
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Build and Test
        run: |
          pod install
          ls -la
          xcodebuild clean build -workspace ownCloud.xcworkspace -scheme ownCloud -configuration Debug -destination "${destination}"
        env:
          destination: ${{ matrix.destination }}
      - name: Archive Failed Tests artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: FailureDiff
          path: FailureDiffs
