name: Calens Changelog
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - fix/*
    - feature/*

jobs:
  build:
    runs-on: ubuntu-16.04
    name: Run Calens Go Script
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - run: go get github.com/restic/calens
             go run .github/workflows/calens/main.go