name: Calens Changelog
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - fix/*
    - feature/*

jobs:
  build:
    runs-on: ubuntu-16.04
    name: Run Calens Go Script
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: addnab/docker-run-action@v1
        with:
          options: -v ${{github.workspace}}:/workspace
          image: toolhippie/calens:latest
          run: calens t /workspace/changelog/CHANGELOG.tmpl
             