name: Calens Changelog
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - fix/*
    - feature/*
    - milestone/*

jobs:
  build:
    runs-on: ubuntu-16.04
    name: Generate Calens Changelog
    steps:
      - uses: actions/checkout@v2
      - name: Run Calens Docker
        uses: addnab/docker-run-action@v1
        with:
          options: -v ${{github.workspace}}:/workspace -w /workspace
          image: toolhippie/calens:latest
          run: calens
      - name: Commit files
        run: |
            ls -la ${{github.workspace}}
            cat ${{github.workspace}}/CHANGELOG.md