name: Calens Changelog
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - fix/*
    - feature/*

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.14' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
	    env:
		  GOPROXY: "https://proxy.golang.org"
      - run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
          go run .github/workflows/calens/main.go